### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by MarouenMechtri**
Change 
neutron port-list -c id -- --device_id b24fc4ad-2d66-4f28-928b-f1cf78075d33 
to 
neutron port-list -c id --device_id b24fc4ad-2d66-4f28-928b-f1cf78075d33

### CODE REVIEW

**Comment by lorin** [comment]
I made some readme changes, could you rebase or merge master first?

**Comment by MarouenMechtri** [comment]
OK it's done.
Thanks

**Comment by lorin** [comment]
I don't see any change to the PR, GitHub still won't let merge it. (If it's a pain, I can just make the change myself).

**Comment by lorin** [comment]
This was merged in as part of https://github.com/lorin/devstack-vm/pull/9

**Pull request closed without merging**
